#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build the Terraform container
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose -f docker-compose.yml build terraform
    fi
fi
