ARG PANGEO_VERSION
FROM pangeo/pangeo-notebook:$PANGEO_VERSION

#RUN conda init
#RUN conda install -y expat gdal
RUN pip3 install s3contents fastparquet psycopg2-binary
COPY --chmod=444 jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
