#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build the Terraform container
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        PROVIDED_ENV=${1:-staging}
        export ENVIRONMENT=${ENVIRONMENT:-$PROVIDED_ENV}
        export CURRENT_UID=$(id -u):$(id -g)
        CONFIGURED_REGION=$(aws configure get region)
        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$CONFIGURED_REGION}
        export S3_SETTINGS_BUCKET=${S3_SETTINGS_BUCKET:-azavea-kubernetes-settings-${AWS_DEFAULT_REGION}}
        # export WORKDIR=$(mktemp -d)
        export DOCKER_GID=$(getent group docker | awk -F: '{print $3}')

        docker-compose -f docker-compose.yml build --build-arg UID=$(id -u) --build-arg GID=$(id -g) terraform
    fi
fi
