#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build the Terraform container
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        export DOCKER_GID=$(getent group docker | awk -F: '{print $3}')

        docker-compose -f docker-compose.yml build --build-arg UID=$(id -u) --build-arg GID=$(id -g) terraform
    fi
fi
