#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0") [environment]
Launch a container environment for interacting with Terraform.  Targets staging environment if not provided, either via the ENVIRONMENT variable or as an argument.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        PROVIDED_ENV=${1:-staging}
        export ENVIRONMENT=${ENVIRONMENT:-$PROVIDED_ENV}
        export CURRENT_UID=$(id -u):$(id -g)
        CONFIGURED_REGION=$(aws configure get region)
        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$CONFIGURED_REGION}
        export S3_SETTINGS_BUCKET=${S3_SETTINGS_BUCKET:-azavea-kubernetes-settings-${AWS_DEFAULT_REGION}}
        export WORKDIR=$(mktemp -d)

        echo "$(tput bold)Entering console for $(tput setaf 1)$ENVIRONMENT$(tput setaf 0) environment$(tput sgr0) (region=$(tput setaf 1)${AWS_DEFAULT_REGION}$(tput setaf 0))"
        docker-compose -f docker-compose.yml run terraform
        rm -rf $WORKDIR
    fi
fi
