#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [environment]
Deploy Kubernetes infrastructure to given environment.  The environment will be obtained with the following precedence:
1. Through the ENVIRONMENT environment variable,
2. As an argument to this script, or
3. If not provided, the default value of \`staging' will be used"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [[ -z "${S3_SETTINGS_BUCKET+x}" ]]; then
            echo "WARNING: No S3_SETTINGS_BUCKET defined, falling back to default"
        fi

        PROVIDED_ENV=${1:-staging}
        export ENVIRONMENT=${ENVIRONMENT:-$PROVIDED_ENV}
        export CURRENT_UID=$(id -u):$(id -g)
        CONFIGURED_REGION=$(aws configure get region)
        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$CONFIGURED_REGION}
        export S3_SETTINGS_BUCKET=${S3_SETTINGS_BUCKET:-azavea-kubernetes-settings-${AWS_DEFAULT_REGION}}

        echo -e "$(tput bold)Deploying infrastructure for $(tput setaf 1)$ENVIRONMENT$(tput setaf 0) environment$(tput sgr0) (region=$(tput setaf 1)${AWS_DEFAULT_REGION}$(tput setaf 0))\nCancel within 3 seconds if not correct..."
        sleep 1
        echo "2..."
        sleep 1
        echo "1..."
        sleep 1

        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra clear 0-hardware
        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra plan 0-hardware
        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra apply 0-hardware

        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra clear 1-system
        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra plan 1-system
        docker-compose -f docker-compose.yml run --rm terraform ./scripts/infra apply 1-system

    fi
fi
