controller:
  workflowNamespaces:
    - argo
server:
  serviceType: LoadBalancer
  servicePort: 443
  servicePortName: https
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  nodeSelector:
    node-type: core
  extraArgs:
    - --auth-mode=sso
  secure: false
  sso:
    clientId:
      name: argo-server-oauth
      key: client_id
    clientSecret:
      name: argo-server-oauth
      key: client_secret
    rbac:
      enabled: true
    scopes:
      - email
      - profile
      - openid
artifactRepository:
  archiveLogs: true
workflow:
  serviceAccount:
    name: default
