enabled: true  # Enabling dask-gateway will install Dask Gateway as a dependency.
# Futher Dask Gateway configuration goes here
# See https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/values.yaml
gateway:
  prefix: "/services/dask-gateway"  # Users connect to the Gateway through the JupyterHub service.
  loglevel: INFO
  nodeSelector:
    node-type: core
  auth:
    type: jupyterhub  # Use JupyterHub to authenticate with Dask Gateway
  extraConfig:
    optionHandler: |
      # see https://gateway.dask.org/cluster-options.html#server-configuration
      from dask_gateway_server.options import Options, Integer, Float, String
      def option_handler(options):
          return {
              "worker_memory": int(options.worker_memory * 2**30),
              "worker_cores": int(options.worker_cores),
              "scheduler_cores": int(options.scheduler_cores),
              "scheduler_memory": int(options.scheduler_memory * 2**30)
          }
      c.Backend.cluster_options = Options(
          Integer("worker_memory", default=4, min=1, max=31, label="Worker memory (GB)"),
          Integer("worker_cores", default=1, min=1, max=8, label="Number of cores per worker"),
          Integer("scheduler_memory", default=8, min=1, max=31, label="Scheduler memory (GB)"),
          Integer("scheduler_cores", default=1, min=1, max=8, label="Number of cores for scheduler"),
          handler=option_handler,
      )
      c.KubeClusterConfig.idle_timeout = 1800
  backend:
    scheduler:
      memory:
        request: "16G"
      extraPodConfig:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - worker
    worker:
      extraContainerConfig:
        env:
        - name: MALLOC_TRIM_THRESHOLD_ # See https://github.com/pangeo-data/rechunker/issues/100#issuecomment-933832834
          value: "0"
      extraPodConfig:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - worker
                  - key: disk-size
                    operator: In
                    values:
                      - large

traefik:
  nodeSelector:
    node-type: core
  service:
    type: ClusterIP  # Access Dask Gateway through JupyterHub. To access the Gateway from outside JupyterHub, this must be changed to a `LoadBalancer`.

rbac:
  enabled: true
